# Generated by Django 3.1.7 on 2021-03-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geojson',
            name='description_long',
        ),
        migrations.AlterField(
            model_name='geojson',
            name='description_short',
            field=models.TextField(),
        ),
    ]
