# Generated by Django 3.1.7 on 2021-03-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210323_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojson',
            name='description_long',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='geojson',
            name='description_short',
            field=models.TextField(null=True),
        ),
    ]
