# Generated by Django 3.1.7 on 2021-03-23 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20210323_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('geojson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.geojson')),
            ],
        ),
    ]
