# Generated by Django 3.1.7 on 2021-03-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20210323_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
