# Generated by Django 3.1.7 on 2021-04-22 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20210323_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojson',
            name='placeId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='geojson',
            name='description_long',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='geojson',
            name='description_short',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='geojson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.geojson'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
