# Generated by Django 3.1.7 on 2021-04-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20210422_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='placeimage',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
