# Generated by Django 3.1.7 on 2021-04-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20210423_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojson',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.FileField(null=True, upload_to='.'),
        ),
    ]
