# Generated by Django 3.1.7 on 2021-04-25 09:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20210425_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojson',
            name='description_long',
            field=tinymce.models.HTMLField(),
        ),
    ]
