# Generated by Django 3.1.7 on 2021-04-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20210425_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geojson',
            name='placeId',
        ),
    ]
