# Generated by Django 3.1.7 on 2021-05-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_remove_geojson_placeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geojson',
            name='my_order',
        ),
    ]
