# Generated by Django 3.1.7 on 2021-05-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_remove_geojson_my_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojson',
            name='description_short',
            field=models.TextField(blank=True),
        ),
    ]
