# Generated by Django 3.1.7 on 2021-05-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20210503_1139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeoJson',
            new_name='Place',
        ),
    ]
