# Generated by Django 3.1.7 on 2021-05-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20210503_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['image_order']},
        ),
        migrations.RenameField(
            model_name='placeimage',
            old_name='my_order',
            new_name='image_order',
        ),
    ]
