# Generated by Django 3.1.7 on 2021-05-03 10:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_auto_20210503_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image_order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
