# Generated by Django 3.1.7 on 2021-05-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_auto_20210503_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeimage',
            old_name='geojson',
            new_name='place',
        ),
    ]
